name: Multiple Testing Framework

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  # schedule:
  #   - cron: '0 10 * * 1'

jobs:
  Nightwatch_test:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
         cache: 'npm'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - run: sudo apt-get install xvfb

      - name: Run Nightwatch tests
        run: xvfb-run --auto-servernum npm test -- --env chrome

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: tests_output  # Adjust this to match the directory where Nightwatch generates test reports
