name : Automated Tests

on: 
 push:
 workflow_dispatch:
 # schedule:

jobs: 
 Nightwatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           cache: 'npm'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:         
          node-version: 21

      - name: Install dependencies
        run: |
            cd Nightwatch
            npm ci
      - run: sudo apt-get install xvfb 

      - name: Run Nightwatch tests
        run: |
            cd Nightwatch
            xvfb-run --auto-servernum npm test -- --env chrome

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: Nightwatch/tests_output  # Adjust this to match the directory where Nightwatch generates test reports

 Postman:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name : Create dir
        run : |
          mkdir SampleArtifact
      #Install Nodejs
      - name : Install Node
        uses: actions/checkout@v4
        with:
           node-version : 12
      # Install Newman and Reporter
      - name : Install Newman
        run : |
          npm install -g newman
          npm install -g newman-reporter-htmlextra 
      #Run Collection
      - name : Run Collection
        run : |
          # newman run "Postman API - Assignmentt.json" -e "Users.postman_environment.json" -r htmlextra --reporter-htmlextra-extract SampleArtifact/report.html
          newman run Postman/Postman API - Assignmentt.json -e Postman/Users.postman_environment.json --reporters cli , htmlextra --reporter-htmlextra-export testArtifacts/htmlreports.html
      #Publish the Report
      - name: Publish report
        uses : actions/upload-artifact@v4
        with:
           name : Reports
           Path : SampleArtifact
    
