name : Automated Tests

on: 
 push:
 workflow_dispatch:
 # schedule:

jobs: 
 Nightwatch:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
            cd Nightwatch
            npm ci
      - run: sudo apt-get install xvfb 

      - name: Run Nightwatch tests
        run: |
            cd Nightwatch
            xvfb-run --auto-servernum npm test -- --env chrome

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: Nightwatch/tests_output  # Adjust this to match the directory where Nightwatch generates test reports
